#!/usr/bin/env bash
echo "🚀 dots-hyprland installer replication development environment"
echo ""
echo "📋 Available commands:"
echo "  update-flake          - Manage flake inputs and GitHub sync"
echo "  compare-modes         - Compare declarative vs writable modes"
echo "  test-python-env       - Test Python virtual environment"
echo "  test-quickshell       - Test quickshell with config"
echo ""
echo "🔄 Flake management:"
echo "  update-flake status   - Show current flake status"
echo "  update-flake update   - Update all flake inputs"
echo "  update-flake verify   - Test configurations build"
echo ""
echo "🎯 Build configurations:"
echo "  nix build .#homeConfigurations.declarative.activationPackage"
echo "  nix build .#homeConfigurations.writable.activationPackage"
echo ""
echo "🔑 Key insight: Both modes use the same Python venv and packages!"
echo "📁 Branch: $(git branch --show-current 2>/dev/null || echo 'unknown')"
echo ""
echo "💡 Run 'update-flake help' for full flake management options"
